name: chat_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  convex_bottom_bar: ^3.0.0
  simple_animations: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  page_transition: ^2.0.9
  image_picker: ^0.8.5+3
  font_awesome_flutter: ^10.1.0
  intl_phone_number_input: ^0.7.0+2
  url_launcher: ^6.0.7
  http: ^0.13.5
  flutter_svg: ^1.1.3
  easy_localization: ^3.0.1
  flutter_phoenix: ^1.0.0
  dropdown_button2: ^1.7.2
  flutter_rating_bar: ^4.0.1
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  firebase_core: ^1.20.1
  file_picker: ^5.0.1
  another_flushbar: ^1.10.29
  pin_code_fields: ^7.4.0
  flutter_secure_storage: ^5.1.0
  dio: ^4.0.6
  cached_network_image: ^3.2.1
  flutter_local_notifications: ^9.7.1
  flutter_native_timezone: ^2.0.0
  firebase_messaging: ^12.0.2
  awesome_notifications: ^0.6.21
  country_code_picker: ^2.0.2
  audioplayers: 0.18.0
  record_mp3: ^3.0.0
  flutter_launcher_icons: ^0.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

module:
  androidX: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/user_profile/
    - assets/group/
    - assets/hotel/
    - assets/translations/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/rubik/Rubik-Regular.ttf
        - asset: fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: fonts/rubik/Rubik-Medium.ttf
          weight: 500
